OPENAI_API_KEY = "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"
QDRANT_URL = "https://0a8835d5-ac48-427a-9c8e-3026091a9793.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "Xb38R-RaE_ZkA7eWFb63-Fl0YmqIvpZ466B4YVJ1kKuYXzOJ9ihwdw"
