OPENAI_API_KEY = "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"
QDRANT_URL = "https://c9f9e2b2-c9cf-4bc0-bfb6-8bb25ba07b37.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "9fHlhZj4on_ywqex_nujlopp0YpiOEayOQRxIiAdPQufvHuJmKVmvg"
