[secrets]
OPENAI_API_KEY = "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"
[qdrant]
QDRANT_URL = "https://c9f9e2b2-c9cf-4bc0-bfb6-8bb25ba07b37.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "9fHlhZj4on_ywqex_nujlopp0YpiOEayOQRxIiAdPQufvHuJmKVmvg"
[elasticsearch]
ES_USER = "elastic"
ES_PASSWORD = "zNtkow6QQXG44G50O0ICR068"
ES_CLOUD_ID = "Hackathon:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJGUwZWY3NjFkNzVjNDQ0ZDE4Y2I4ZGU2MTlmZGYxNjJiJDg2ZjI5MjExYTBkODQ1Y2ZiYzc4ZDgwMTczMzRlOTBj"
